service: dance-schedules-nyc
tenant: augustusostow
app: dance-aggregator

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  timeout: 900

functions:
  cunningham:
    handler: handler.cunningham_handler
    events:
      - schedule: cron(0 12 * * ? *)
  dance_wave:
    handler: handler.dance_wave_handler
    events:
      - schedule: cron(30 12 * * ? *)
  gibney:
    handler: handler.gibney_handler
    events:
      - schedule: cron(0 13 * * ? *)
  mark_morris:
    handler: handler.mark_morris_handler
    events:
      - schedule: cron(30 13 * * ? *)
  movement_research:
    handler: handler.movement_research_handler
    events:
      - schedule: cron(0 14 * * ? *)
  peridance:
    handler: handler.peridance_handler
    events:
      - schedule: cron(30 14 * * ? *)

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    useDownloadCache: true
    useStaticCache: true

  alerts:
    stages:
      - dev
    topics:
      alarm:
        topic: ${self:service}-dev-alerts-alarm
        notifications:
          - protocol: email
            endpoint: augustusostow@gmail.com
    alarms:
      - functionErrors
      - functionThrottles
